### ISSUE TITLE
HTTP method name in uppercase is invalid in swagger

### ISSUE THREAD

**Issue by yunhao** [luckymarmot/Paw-SwaggerGenerator#2]
I noticed that this plugin has been updated recently. In the new version,  all the HTTP method names are in uppercase, which does not work in swagger 2 and 3. And now I have to change all of the method names to lowercase to make it works again. (change 'GET' to 'get', 'POST' to 'post')
![2017-05-13 21 28 50](https://cloud.githubusercontent.com/assets/10205466/26025858/3321f9c2-3823-11e7-97fb-31e20ddb3e96.png)
![image](https://cloud.githubusercontent.com/assets/10205466/26025953/d9958890-3824-11e7-9ce8-70096c8efb8d.png)
![image](https://cloud.githubusercontent.com/assets/10205466/26025957/e6c4ebb4-3824-11e7-87ff-df4eb0d5d22d.png)

And according to the image from paw website, the generator made lowercase name in the past. It did work for me in lowercase.
![image](https://cloud.githubusercontent.com/assets/10205466/26025945/c7f3456e-3824-11e7-8539-a49763e98bf3.png)

**Comment by JonathanMontane** [comment]
Thanks for the report, this will be fixed in the next release!
