### ISSUE TITLE
Post request Parameters are not all recognized after the update

### ISSUE THREAD

**Issue by MoathOthman** [luckymarmot/Paw-SwaggerGenerator#3]
Hi guys,

After the swagger code generator latest update , the generated Post requests where _content-Type is application/x-www-form-urlencoded_   do not include all the parameters , only one or non. 

before the update they were generated successfully , tested on the same api request. 

thnx

**Comment by JonathanMontane** [comment]
Thanks for the report! This was a stupid error that should be fixed in the next release.

**Comment by MoathOthman** [comment]
Thanx @JonathanMontane  its fixed now .
