### ISSUE TITLE
Invalid generated consumes field

### ISSUE THREAD

**Issue by garetht** [luckymarmot/Paw-SwaggerGenerator#5]
When working with URL-encoded form data parameters, the extension generates a `consumes` field with value `application/x-www-form-urlencoded; charset=utf-8`. Swagger does not recognize this and throws the error `Operations with Parameters of "in: formData" must include "application/x-www-form-urlencoded" or "multipart/form-data" in their "consumes" property`.

*Expected*
The `consumes` property should just be `application/x-www-form-urlencoded`.

**Comment by JonathanMontane** [comment]
Thanks for the report, I'll look into it.

**Comment by JonathanMontane** [comment]
@garetht this should be fixed in the latest release.
